apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: eulersidentity2718@gmail.com
    privateKeySecretRef:
      name: godaddy-api-key-secret
    solvers:
    - selector:
        dnsNames:
        - '*.cloudpoet.in'
      dns01:
        webhook:
          config:
            apiKeySecretRef:
              name: godaddy-api-key
              key: token
            production: true
            ttl: 600
          solverName: godaddy

