apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: homelab-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.150-192.168.1.165
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb-system
spec:
  ipAddressPools:
  - homelab-ip-pool
